[[profiles]]
name = "default"
synced_files = [
    ".config/fish",
    ".config/ghostty",
    ".config/helix",
    ".config/starship.toml",
    ".config/zed",
]

[[profiles.packages]]
name = "yazi"
description = "File Manager"
manager = "dnf"
package_name = "yazi"
binary_name = "yazi"

[[profiles.packages]]
name = "fzf"
description = "Fuzy Finder"
manager = "dnf"
package_name = "fzf"
binary_name = "fzf"
