version = 1

[common]
synced_files = []

[[profiles]]
name = "default"
synced_files = [
    ".config/fish",
    ".config/ghostty",
    ".config/helix",
    ".config/starship.toml",
    ".config/yazi",
    ".config/zed",
    ".config/zellij",
]

[[profiles.packages]]
name = "yazi"
description = "File Manager"
manager = "custom"
binary_name = "yazi"
install_command = "./package_scripts/yazi.sh"
existence_check = "yazi"

[[profiles.packages]]
name = "fzf"
description = "Fuzy Finder"
manager = "dnf"
package_name = "fzf"
binary_name = "fzf"

[[profiles.packages]]
name = "helix"
description = "Editor de terminal"
manager = "dnf"
package_name = "helix"
binary_name = "hx"
