onboarding = false
[ui]
agent_panel_scope = "all"


[theme]
name = "terminal"
auto_switch = false

[ui.toast]
delivery = "herdr"

[keys]
prefix = "ctrl+h"

[[keys.command]]
key = "prefix+alt+o"
type = "pane"
command = "git"
description = "Run octo Git Tool in temp pane"

[[keys.command]]
key = "prefix+alt+y"
type = "pane"
command = "yazi"
description = "Run yazi File Explorer in temp pane"


