[colors.primary]
background = '#141313'
foreground = '#e5e2e0'

[colors.cursor]
text = '#141313'
cursor = '#e5e2e0'

[colors.vi_mode_cursor]
text = '#141313'
cursor = '#c8c7bc'

[colors.search.matches]
foreground = '#474740'
background = '#c2c8c2'

[colors.search.focused_match]
foreground = '#474740'
background = '#c8c7bc'

[colors.footer_bar]
foreground = '#474740'
background = '#e5e2e0'

[colors.hints.start]
foreground = '#474740'
background = '#c8c6c1'

[colors.hints.end]
foreground = '#474740'
background = '#c8c6c1'

[colors.selection]
text = '#c8c7be'
background = '#474740'


[colors.normal]
black   = '#474740'
red     = '#ffb4ab'
green   = '#c8c7bc'
yellow  = '#c8c6c1'
blue    = '#c2c8c2'
magenta = '#c8c7bc'
cyan    = '#c8c6c1'
white   = '#e5e2e0'


[colors.bright]
black   = '#929189'
red     = '#ffb4ab'
green   = '#c8c7bc'
yellow  = '#c8c6c1'
blue    = '#c2c8c2'
magenta = '#c8c7bc'
cyan    = '#c8c6c1'
white   = '#e5e2e0'


[colors.dim]
black   = '#474740'
red     = '#ffb4ab'
green   = '#c8c7bc'
yellow  = '#c8c6c1'
blue    = '#c2c8c2'
magenta = '#c8c7bc'
cyan    = '#c8c6c1'
white   = '#e5e2e0'
