[colors.primary]
background = '#eefcff'
foreground = '#111d20'
 
[colors.cursor]
text = '#111d20'
cursor = '#334a50' 
 
[colors.vi_mode_cursor]
text = '#eefcff'
cursor = '#006c46' 
 
[colors.search.matches]
foreground = '#cde7ed' 
background = '#006876' 
 
[colors.search.focused_match]
foreground = '#cde7ed' 
background = '#006c46' 
 
[colors.footer_bar]
foreground = '#cde7ed' 
background = '#263235' 
 
[colors.hints.start]
foreground = '#cde7ed' 
background = '#256a4a' 
 
[colors.hints.end]
foreground = '#cde7ed' 
background = '#256a4a' 
 
[colors.selection]
text = '#eefcff'
background = '#006c46'
 
 
[colors.normal]
black = '#181818' 
red = '#ba1a1a' 
green = '#006c46' 
yellow = '#72daa5' 
blue = '#006c46' 
magenta = '#006876' 
cyan = '#256a4a' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 