[colors.primary]
background = '#10131c'
foreground = '#e0e2ef'

[colors.cursor]
text = '#10131c'
cursor = '#e0e2ef'

[colors.vi_mode_cursor]
text = '#10131c'
cursor = '#56d6f5'

[colors.search.matches]
foreground = '#3f4759'
background = '#afc6ff'

[colors.search.focused_match]
foreground = '#3f4759'
background = '#56d6f5'

[colors.footer_bar]
foreground = '#3f4759'
background = '#e0e2ef'

[colors.hints.start]
foreground = '#3f4759'
background = '#85d2e7'

[colors.hints.end]
foreground = '#3f4759'
background = '#85d2e7'

[colors.selection]
text = '#bfc6dc'
background = '#3f4759'


[colors.normal]
black   = '#3f4759'
red     = '#ffb4ab'
green   = '#56d6f5'
yellow  = '#85d2e7'
blue    = '#afc6ff'
magenta = '#56d6f5'
cyan    = '#85d2e7'
white   = '#e0e2ef'


[colors.bright]
black   = '#8990a5'
red     = '#ffb4ab'
green   = '#56d6f5'
yellow  = '#85d2e7'
blue    = '#afc6ff'
magenta = '#56d6f5'
cyan    = '#85d2e7'
white   = '#e0e2ef'


[colors.dim]
black   = '#3f4759'
red     = '#ffb4ab'
green   = '#56d6f5'
yellow  = '#85d2e7'
blue    = '#afc6ff'
magenta = '#56d6f5'
cyan    = '#85d2e7'
white   = '#e0e2ef'
