[general]
import = [
    "~/.config/alacritty/themes/noctalia.toml",
]

[window]
decorations = "Full"
padding = { x = 20, y = 20 }

[font]
normal = { family = "CommitMono Nerd Font Mono" }
size = 14

[colors]
transparent_background_colors = true

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Underline", blinking = "Always" }
