[general]
import = [
    "~/.config/alacritty/themes/noctalia.toml",
]

[window]
decorations = "Full"
padding = { x = 20, y = 20 }

[terminal]
shell = { program = "/usr/bin/fish", args = ["-C", "fastfetch"] }

[font]
normal = { family = "CommitMono Nerd Font Mono" }
size = 14

[colors]
transparent_background_colors = true

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Underline", blinking = "Always" }

[keyboard]
bindings = [
    { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" },
]
