[manager]
layout = [0, 1, 0]

[opener]
edit = [
  { run = "$EDITOR %s", desc = "Edit in default editor", block = true },
  { run = "neovide %s", desc = "Edit in neovide", orphan = true },
]
terminal-dir = [
  { run = 'alacritty --working-directory %s1', orphan = true, desc = "Alacritty acá" },
]
opencode-dir = [
  { run = 'alacritty --working-directory %s1 -e opencode', orphan = true, desc = "OpenCode acá" },
]
hx-dir = [
  { run = 'alacritty --working-directory %s1 -e hx', orphan = true, desc = "Helix acá" },
]
terminal-file = [
  { run = 'alacritty --working-directory %d1', orphan = true, desc = "Alacritty acá" },
]
opencode-file = [
  { run = 'alacritty --working-directory %d1 -e opencode', orphan = true, desc = "OpenCode acá" },
]
hx-file = [
  { run = 'alacritty --working-directory %d1 -e hx %s1', orphan = true, desc = "Helix acá" },
]

[open]
rules = [
  # Folder
  { url = "*/", use = [ "open", "terminal-dir", "opencode-dir", "hx-dir", "edit", "reveal" ] },
  # Text
  { mime = "text/*", use = [ "open", "edit", "reveal", "terminal-file", "opencode-file", "hx-file" ] },
  # Image
  { mime = "image/*", use = [ "open", "reveal", "terminal-file", "opencode-file" ] },
  # Media
  { mime = "{audio,video}/*", use = [ "open", "play", "reveal", "terminal-file", "opencode-file" ] },
  # Code
  { mime = "application/{json,ndjson,javascript,wine-extension-ini}", use = [ "open", "edit", "reveal", "terminal-file", "opencode-file", "hx-file" ] },
  # Archive
  { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", use = [ "extract", "reveal" ] },
  # Empty file
  { mime = "inode/empty", use = [ "open", "edit", "reveal", "terminal-file", "opencode-file", "hx-file" ] },
  # Virtual file system
  { mime = "vfs/{absent,stale}", use = "download" },
  # Trash
  { mime = "trash/**", use = [ "open", "trash" ] },
  # Fallback
  { url = "*", use = [ "open", "edit", "reveal", "terminal-file", "opencode-file", "hx-file" ] },
]
